name: CI Pipeline

on:
  push:
    branches: [ "sesi31-loadtest" ]
  pull_request:
    branches: [ "sesi31-loadtest" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --coverage

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=minyong007_tugas-project-digital-skola-devops
            -Dsonar.organization=minyong007
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Install k6
        run: sudo apt-get update && sudo apt-get install -y k6

      - name: Run k6 load test
        run: k6 run loadtest/script.js
